overrides:
  ceph:
    fs: xfs
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
    - log bound mismatch
    - failed to encode map e
tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
    min_in: 4
    sighup_delay: 0
- print: "**** done thrashosds 3-thrash"
