meta:
- desc: |
   randomly kill and revive osd
   small chance to increase the number of pgs
overrides:
  ceph:
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
    - log bound mismatch
    - failed to encode map e
tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
    min_in: 4
- print: "**** done thrashosds 3-thrash"
